# Project name
name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

# Snapshot routing
snapshots:
  dbt_project:
    +target_schema: liquor_snapshots

models:
  dbt_project:
    +materialized: view 

    staging:
      +materialized: view
      +schema: liquor_silver

    intermediate:
      +materialized: table
      +schema: liquor_silver

    dimensions:
      +materialized: table
      +schema: liquor_silver

    marts:
      +materialized: table
      +schema: liquor_gold
      
      reporting:
        +materialized: view

vars:
  default_unknown_string: "UNASSIGNED"
